import type { ResumeContent } from "../types";

export const resumeContent: ResumeContent = {
  profile: {
    name: "Christian Rodriguez",
    role: "OutSystems Expert Developer",
    highlights: ["Low-Code Expert", "Solutions Builder", "Problem Solver"],
    bio: "OutSystems Expert certified developer with 5+ years of experience building secure, scalable, and high-performance enterprise applications. Specialized in full-cycle development, complex integrations, workflow automation, and agentic/AI implementations using the OutSystems platform.",
    summary: [
      "OutSystems developer with a strong track record delivering mission-critical solutions for government, healthcare, financial and enterprise organizations. Experienced in full-cycle development, integrations, workflow automation, and modern agentic/AI implementations that drive efficiency and improve decision-making.",
      "Committed to clean architecture, performance, security, and continuous improvement.",
    ],
  },
  contacts: [
    {
      label: "Location",
      value: "San Juan, Puerto Rico",
      icon: { type: "ui", key: "location" },
    },
    {
      label: "Email",
      value: "christian.rodriguez@upr.edu",
      href: "mailto:christian.rodriguez@upr.edu",
      icon: { type: "ui", key: "email" },
    },
    {
      label: "LinkedIn",
      value: "LinkedIn - Christian Rodriguez",
      href: "https://linkedin.com/in/christian-rodriguez",
      icon: { type: "brand", key: "linkedin" },
    },

    {
      label: "OutSystems",
      value: "OutSystems Profile",
      href: "https://www.outsystems.com/profile/na7cyeioxw",
      icon: { type: "brand", key: "outsystemsLogo" },
    },
  ],
  expertise: [
    "OutSystems Platform (Traditional and Reactive)",
    "Full-Cycle Development",
    "UI/UX and Responsive Design",
    "Business Logic and Server Actions",
    "Integrations and REST/SOAP APIs",
    "Data Modeling and Optimization",
    "Workflow and Case Management",
    "Agentic / AI Implementations",
    "Reporting and Data Visualization",
    "Security and Access Control",
    "Testing, Debugging and Optimization",
    "Cloud, DevOps and CI/CD",
  ],
  domains: [
    "Government and Public Safety",
    "License and Certification Management",
    "Case and Workflow Management",
    "Healthcare and Insurance Claims",
    "Financial Services and Banking",
    "Reporting, Analytics and Dashboards",
    "Document Management",
    "Security, Roles and Compliance",
    "AI / Agentic Solutions and Automation",
  ],
  experiences: [
    {
      year: "2024",
      period: "Present",
      company: "Puerto Rico Police Department (PRPD)",
      role: "OutSystems Developer",
      summary:
        "Developed and maintained internal applications for processing and managing a wide array of cases and licenses. Implemented agentic solutions, workflow automation, integrations, reporting and dashboards to support daily operations.",
      tags: [
        "Case Management",
        "Licensing and Certifications",
        "Integrations",
        "AI / Agentic",
        "Dashboards",
      ],
      logoVariant: "police",
      logoText: "POLICIA",
    },
    {
      year: "2023",
      company: "National Government Services (Anthem, Inc.)",
      role: "OutSystems Developer",
      summary:
        "Implemented internal application as front end for mainframe system responsible for generating letters for approving, denying or general notifications about medical insurance claims.",
      tags: [
        "Mainframe Integration",
        "Claims Processing",
        "Workflows",
        "UI/UX",
      ],
      logoVariant: "ngs",
      logoText: "NGS",
    },
    {
      year: "2022",
      company: "Horne: USA and Horne: Puerto Rico",
      role: "OutSystems Developer",
      summary:
        "Implemented a wide range of internal and public-facing applications including calendar apps, media approval, HR ticketing, waste and management system for citizens of Arkansas, and government grant management applications.",
      tags: ["Portals", "Service Center", "Grants Management", "Integrations"],
      logoVariant: "horne",
      logoText: "HORNE",
    },
    {
      year: "2021",
      company: "Santander Bank",
      role: "SQL / Reporting Consultant",
      summary:
        "Provided SQL consultancy for scheduled bankruptcy weekly reports. Modified and debugged WAVE reports for internal checks and balances of specific accounts.",
      tags: ["SQL", "WAVE Reports", "Data Analysis", "Scheduled Jobs"],
      logoVariant: "santander",
    },
    {
      year: "2020",
      company: "Oil and Gas Monitoring Platform",
      role: "React JS Developer",
      summary:
        "Implemented responsive web and mobile flows to monitor remote oil rig instrumentation and global positioning to support field operations and decision-making.",
      tags: ["React JS", "API Integration", "Maps / GPS", "User Flows"],
      logoVariant: "oil",
    },
    {
      year: "2019",
      company: "Personas (Todo1) and Bancolombia",
      role: "Application Developer",
      summary:
        "Implemented end user flows with security layers and API integrations for the public bank applications Personas for Todo1 and Bancolombia.",
      tags: ["OutSystems", "APIs", "Security", "User Experience"],
      logoVariant: "personas",
    },
  ],
  certifications: [
    "Expert Developer (O11) - Since Jun 23, 2026",
    "Associate Developer (ODC) - Since Jun 03, 2026",
    "Associate Developer (O11) - Since Jun 01, 2020",
    "Associate Traditional Web Developer (O11) - Since Sep 30, 2019",
    "Front-end Developer Specialist (O11 and ODC) - Since Jun 23, 2026",
    "Web Developer Specialist (ODC) - Since Jun 13, 2026",
    "Web Developer Specialist (O11) - Since Jun 13, 2026",
    "Architecture Specialist (O11) - Since May 30, 2026",
    "Security Specialist (O11 and ODC) - Since Oct 06, 2023",
    "Mobile Developer Specialist (O11 and ODC) - Since Jun 01, 2020",
  ],
  stack: [
    { label: "OutSystems", icon: { type: "brand", key: "outsystemsLogo" } },
    { label: "HTML5", icon: { type: "brand", key: "html5" } },
    { label: "CSS3", icon: { type: "brand", key: "css3" } },
    { label: "JavaScript", icon: { type: "brand", key: "javascript" } },
    { label: "SQL", icon: { type: "ui", key: "database" } },
    { label: "REST APIs", icon: { type: "ui", key: "api" } },
    { label: "Git", icon: { type: "brand", key: "git" } },
    { label: "Docker", icon: { type: "brand", key: "docker" } },
    { label: "Azure", icon: { type: "brand", key: "azure" } },
    { label: "AWS", icon: { type: "brand", key: "amazonwebservices" } },
    { label: "PostgreSQL", icon: { type: "brand", key: "postgresql" } },
    { label: "Power BI", icon: { type: "ui", key: "analytics" } },
    { label: "Microsoft 365", icon: { type: "ui", key: "apps" } },
  ],
  facts: [
    { text: "Based in San Juan, Puerto Rico", icon: "location" },
    { text: "Open to remote opportunities (US / PR)", icon: "globe" },
    { text: "Available to start immediately", icon: "availability" },
    {
      text: "Bilingual: English (Professional) / Spanish (Native)",
      icon: "languages",
    },
  ],
  quote:
    "Building scalable solutions, leveraging AI to solve real business problems.",
  availability: "Actively looking for new opportunities",
};
